eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.application.name}
#    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/actuator/health
    home-page-url: http://${eureka.instance.ip-address}:${server.port}/
#logging:
#  config: classpath:log4j2.xml
#  level:
#    com:
#      study:
#        microsuser:
#          dao: debug
server:
  port: 8201
  undertow:
    accesslog:
      enabled: true
      dir: logs/server
spring:
  application:
    name: micros-user
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
    time-zone: GMT+8
feign:
  hystrix:
    enabled: true
#  okhttp:
#    enabled: true
#hystrix:
#  threadpool:
#    default:
#      coreSize: 200
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
##使用熔断聚合监控时，Finchley.M9 版本，Actuator这个包变化了，默认只暴露health等几个端点需要加上如下配置才能 使监控生效
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,hystrix.stream
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always
mybatis:
  mapper-locations: classpath:mappers/*.xml
    #pojo类所在包路径
  type-aliases-package: com.study.microsuser.model
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql